### ISSUE TITLE
beepOnScan behaviour on iOS

### ISSUE THREAD

**Issue by rowdyrabouw** [EddyVerbruggen/nativescript-barcodescanner#113]
With beepOnScan set to true you will always get a sound on iOS, even if you have sound disabled.

**iOS**
sound enabled: beeps
sound disabled: still beeps :-(

**Android**
sound enabled: beeps
sound disabled; no beep :-)

**Comment by EddyVerbruggen** [comment]
Interesting. So to fix that we'd need to determine whether or not the device is muted before playing a sound. That turns out to be a hard problem to solve and has changed quite a bit over the last 7 versions of iOS.

It would be best to change the current `AudioServicesPlaySystemSound` to `AVAudioPlayer` as mentioned [here](https://stackoverflow.com/questions/10855874/audioservicesplaysystemsound-volume).

**Comment by EddyVerbruggen** [comment]
Btw, I used to leverage `AVAudioPlayer` with this plugin the past: #93.

But removed it because the bundled `.mp3` file was not found inside a webpacked app.

**Comment by EddyVerbruggen** [comment]
Found a much better way to reference the bundled `.caf` file, so now we're using `AVAudioPlayer` again, which honors the mute and volume settings. Available in 2.7.0 from npm (now).

**Comment by rowdyrabouw** [comment]
WOW, fast fix!
Will try today.

Didn't get a reminder from Sibbell, because you haven't tagged a release her yet. ;-)

**Comment by EddyVerbruggen** [comment]
Tagged.

**Comment by rowdyrabouw** [comment]
Co-worker tested it and works great. Thanks!
