### ISSUE TITLE
online barcodescanner.android.js is incorrectly compiled - throws exception 

### ISSUE THREAD

**Issue by ahhatem** [EddyVerbruggen/nativescript-barcodescanner#152]
The file has a lot of statements that seem to be incorrectly compiled or something:
  intent.putExtra(com.google.zxing.client.android.Inthents.Scan.SHOW_FLIP_CAMERA_BUTTON, true);
(no quotes)
This throws an exception that cannot find  zxing in undefined.
 When manually changed to:
intent.putExtra("com.google.zxing.client.android.Intents.Scan.SHOW_FLIP_CAMERA_BUTTON", true);
(with quotes)
it seems to be fine.

**Comment by EddyVerbruggen** [comment]
Yes, but that will not work because `com.google.zxing.client.android.Intents.Scan.SHOW_FLIP_CAMERA_BUTTON` refers to a constant in a Java class which is not equals to the `"com.google.zxing.client.android.Intents.Scan.SHOW_FLIP_CAMERA_BUTTON"` String constant.

The problem can probably be solved by removing you platforms/android folder and doing a fresh build (making sure the barcodescanner .aar is actually in the platforms folder).

**Comment by ahhatem** [comment]
Actually the files are there... Any why did it work on my setup when I have done this change?

**Comment by EddyVerbruggen** [comment]
[This is the constant the code refers to](https://github.com/EddyVerbruggen/barcodescanner-lib-aar/blob/e8fed10020f06b9de0ebadcbeea408175a96a94a/barcodescanner/src/main/java/com/google/zxing/client/android/Intents.java#L180), so at runtime it evaluates to `"SHOW_FLIP_CAMERA_BUTTON"`. I'd guess that with your change the `showFlipCameraButton` boolean no longer works?

**Comment by ahhatem** [comment]
You are right. I did have to change more with their correct values from the referenced file. It works and resolves the barcodes correctly, but it throws exceptions all over the place. 

I tried to copy the .aar file from the demo version and (without these changes) the results are the same.

Any advises on to make it work the proper way?
