### ISSUE TITLE
After updating NS core modules to 5.0.0 they are not working

### ISSUE THREAD

**Issue by karo-dc** [EddyVerbruggen/nativescript-barcodescanner#169]
I am using the native barcode scanner for ios, which is shown in your examples, and it's not working with 5.0.0. But when I revert to NS core modules to 4.2.1 it's working again

**Comment by EddyVerbruggen** [comment]
Android / iOS / both?

**Comment by jaasaria** [comment]
what's the error @karo-dc ? Mine just installed ns-barcode and im receiving `Cannot read property 'hasCameraPermission'` hmm maybe with the ns5 version?

**Comment by karo-dc** [comment]
I have tried on iOS and there were no exceptions. I was only using the template part, without code.

**Comment by karo-dc** [comment]
@EddyVerbruggen  Also, I have a question: I can customize the camera screen in iOS. But I cannot do that for Android. The documentation says I can use MLKit for that. But I don't want to use that: I want to use this one plugin for both platforms.

**Comment by EddyVerbruggen** [comment]
@karo-dc Be as it may, but you can't use this plugin to customize the UI for Android. Period.

**Comment by EddyVerbruggen** [comment]
To be clear (for anyone reading this): the issue here is that with NativeScript 5 the [UI-declared](https://github.com/EddyVerbruggen/nativescript-barcodescanner/blob/895f0f4d145b5d7afbaee5974d4ddbee2390bf6d/demo-ng/app/item/item-detail.component.html#L10-L17) scanner doesn't show up. If you invoke the plugin [from JS/TS](https://github.com/EddyVerbruggen/nativescript-barcodescanner/blob/895f0f4d145b5d7afbaee5974d4ddbee2390bf6d/demo-ng/app/item/item-detail.component.ts#L34-L46) it does.

Not sure yet what the solution should be.

**Comment by EddyVerbruggen** [comment]
Found a way to fix this (which is also compatible with older {N} versions). Now available from npm in version 2.7.9. Thanks for reporting this y'all!

**Comment by karo-dc** [comment]
@EddyVerbruggen thank you too!
