### ISSUE TITLE
Injecting Error

### ISSUE THREAD

**Issue by ShyshkovOleg** [EddyVerbruggen/nativescript-barcodescanner#194]
- IOS, Android Errors:
If I inject into the constructor I get -  TypeError: undefined is not an object (evaluating 'type.hasOwnProperty')
If i embed in Ios WITH OUT injecting in the Componen: Error: Uncaught (in promise): TypeError: `AVAudioSession.sharedInstance().setCategoryModeOptionsError` is not a function

Does this plugin has some conflicts with plugin firebase?

**Comment by EddyVerbruggen** [comment]
@ShyshkovOleg Interesting.. that error is probably triggered by a very recent change to this plugin, see:

https://github.com/EddyVerbruggen/nativescript-barcodescanner/blob/1816d2611a266da272ed2361c5122ad602060e24/src/barcodescanner.ios.ts#L20

However, I'm not sure why this results in an error. Unless you're running on iOS 9, because I just found out this function was added in iOS 10: https://developer.apple.com/documentation/avfoundation/avaudiosession/1771734-setcategory?language=objc

**Comment by ShyshkovOleg** [comment]
Hi, @EddyVerbruggen . I'm trying on IOS 9.3.5
What about android(and ios) error where I want to inject to a component constructor for a fullscreen mode ?

**Comment by EddyVerbruggen** [comment]
OK, then I'll add a guard for iOS 10 minimum. Note that iOS 9 will still work, it's just that [this fix](https://github.com/EddyVerbruggen/nativescript-barcodescanner/issues/192) won't be applied.

You can stick to 3.0.3 for iOS 9, until 3.1.1 is released.

And regarding the injection issue: there's no need to inject it really. Just do do `new BarcodeScanner()` wherever you need it.

**Comment by ShyshkovOleg** [comment]
Thank's for your response Eddy.
P.S. Nativescript ROKS with your plugins. :)

**Comment by EddyVerbruggen** [comment]
Thanks mate! I've just pushed 3.1.1 to npm, so it should work on iOS 9 again.
