### ISSUE TITLE
continuous scanning progress

### ISSUE THREAD

**Issue by meceo** [EddyVerbruggen/nativescript-barcodescanner#54]
I am wondering if there is a possibility to have a message visible while using continuous scanning. The message would represent a progress. I.e "4/10 items scanned". The message would get updated in continuousScanCallback (5/10, 6/10 and so on).

What do you think?

**Comment by EddyVerbruggen** [comment]
Nice idea. Have you tried to show a Toast message?

**Comment by meceo** [comment]
@EddyVerbruggen I thought about something permanent, but toast message does the job as well. Thank you.

**Comment by EddyVerbruggen** [comment]
Good to know, I'll leave this open as a possible future enhancement.

**Comment by renestalder** [comment]
Am I right that when using continuous scanning, that e.g. alert is suppressed and not shown? Is it anyway possible to add overlays and dialogs during continuous scanning with the current version of barcodescanner?

**Comment by EddyVerbruggen** [comment]
@renestalder did you try a Toast?

**Comment by renestalder** [comment]
@EddyVerbruggen That's not what I'm looking for. I need full fledged modals with content an layout, but before trying this, I would like to know, If this is even possible with the continuous scanning function, since I assume even alert gets suppressed.

(Also I'm making an iOS app at the moment. Does iOS even have something like toast notifications?)

**Comment by EddyVerbruggen** [comment]
There's a Toast plugin that supports both. Or use nativescript-feedback as an alternative.

I haven't tried any overlay so please let us know what you can figure out.

**Comment by renestalder** [comment]
Well, the problem is still existing. Everything I want to do to the UI inside the continuousScanCallback function gets suppressed and not shown to the user.

What I'm doing wrong?

```js
const scanOptions: ScanOptions = {
    formats: 'QR_CODE, CODE_128',
    // iOS only, default 'Close'
    cancelLabel: 'EXIT. Also, try the volume buttons!',
    // Android only, default is 'Place a barcode inside the viewfinder rectangle to scan it.'
    message: 'Use the volume buttons for extra light',
    showFlipCameraButton: true,
    preferFrontCamera: false,
    showTorchButton: true,
    torchOn: false,
    resultDisplayDuration: 500,
    orientation: 'portrait',
    openSettingsIfPermissionWasPreviouslyDenied: true,
    continuousScanCallback: (result) => {
        dialogs.alert('Sent request to server...').then(() => console.log('Closed'));
        this.eventDetailsService.scan(result.text, this.event).subscribe(scanResult => {
            this.event = scanResult.event;
        },
            error => alert(error));
        console.log(result.format + ': ' + result.text);
        // TODO: Interface Notification that ticket was scanned successfully
    }
};
```

The `dialogs.alert`doesn't show up on the ui. But based on my logs of the `eventDetailsService` I can clearly say that the continuousScanCallback is called.

The `dialogs.alert` also is correct, since I try it outside of this function first.

**Comment by EddyVerbruggen** [comment]
That's what you concluded 3 weeks ago right, that Alerts can't overlay the scanner. Did you try the Toast as an alternative?

**Comment by renestalder** [comment]
I really appreciate that you try to help, but as already stated, I don't need a toast. I need a modal. It's quite the same case as @meceo has, but with a different solution.

Based on my statements for help I would have expected an answer like “The Barcode Scanner doesn't support modals in the continuousScanning process because of X and Y“ or “You should be able to overlay other components by doing X or Y“. Toasts don't help. They are not modals.

Anyway, for now, I assume this is the wanted behavior or a technical limitation. I now used the default scanning process to show a modal outside of the scanner and go back to the scanning process when the OK button in my modal is clicked.

**Comment by EddyVerbruggen** [comment]
Like I said, I didn't try it, but if you can't get it to work then I'm sure it's a technical limitation. I can imagine it is because the scanner (on Android at least) is an entirely different Activity.

Still, leaving this open because perhaps some day one of us has a brainwave and figures it out.

**Comment by maatthc** [comment]
Hey,
perhaps this could be used as a base implementation for this on Android: https://github.com/journeyapps/zxing-android-embedded

**Comment by Burgov** [comment]
@EddyVerbruggen would that work? ^^

**Comment by EddyVerbruggen** [comment]
Dunno, give it a shot?

**Comment by EddyVerbruggen** [comment]
Embedding a barcode scanner is now possible with the Firebase plugin: https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/ML_KIT.md#barcode-scanning

**Comment by renestalder** [comment]
> Embedding a barcode scanner is now possible with the Firebase plugin

How is this related to the initial request? I still would love to see the proposal as actual feature.

**Comment by EddyVerbruggen** [comment]
@renestalder You requested a way to have layout around the scanner, right? That's not possible with this plugin (on Android), but it is with the other one I created. Feel free to send a PR, but I don't see a way to add it to this plugin without rewriting the damn thing.
